springdoc:
  api-docs.path: /api-docs
spring:
  servlet:
    multipart:
      maxFileSize: 50MB
      max-file-size: 50MB
      maxRequestSize: 50MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.howtodoinjava: DEBUG
    org.hibernate: DEBUG
    org.springframework.security: DEBUG
secret: gdsfsfdvsdfvdfvrtgtregfrevgrtgvfrevgretvdfvdfvfdvdfvdfvtrvtrcdefcefdcefkjcneirfcuierhciurhcuier
server:
  tomcat:
    maxSwallowSize: -1
    max-swallow-size: -1

