springdoc:
  api-docs.path: /api-docs
spring:
  servlet:
    multipart:
      maxFileSize: 50MB
      max-file-size: 50MB
      maxRequestSize: 50MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      hbm2ddl:
        auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect1
      jdbc:
        batch_size: 500
      order_inserts: true
      order_updates: true
      default_batch_fetch_size: true
      properties:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

        show_sql: true
        logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    org.springframework.security: DEBUG
secret: gdsfsfdvsdfvdfvrtgtregfrevgrtgvfrevgretvdfvdfvfdvdfvdfvtrvtrcdefcefdcefkjcneirfcuierhciurhcuier
server:
  tomcat:
    maxSwallowSize: -1
    max-swallow-size: -1

